### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by chasers** [danschultzer/phoenix_oauth2_provider#17]
Was wiring this up and #15 helped quite a bit since I'm in Phoenix 1.4.

Got pretty far but have a question.  I'm using this for https://github.com/Logflare/logflare which ultimately needs a Cloudflare app.  I need to be an Oauth2 server for that.  I got to the point where I can request authorization and it sends me back to Cloudflare.  Then Cloudflare calls this https://github.com/danschultzer/ex_oauth2_provider#authorization-code-grant but the `client-secret` is passed as basic auth in the header it looks like.  You can see that request here: https://cl.ly/a211d29e3a9a/Screen%20Shot%202019-02-12%20at%2010.23.01%20AM.png  

Is that something I'll be able to work around with this library or should I go another route?

Thanks!!

**Comment by niccolox** [comment]
glad its not just me

**Comment by danschultzer** [comment]
You can ignore client secret, [by setting it to an empty string](https://github.com/danschultzer/ex_oauth2_provider/issues/16#issuecomment-364790906). I’m not completely sure how the cloudflare app works, but sounds like you will manage both sides so client secret isn’t necessary.

**Comment by chasers** [comment]
Gotcha ... thanks for being so responsive here btw.

Looks like I was able to get it to issue me an access token but when I made the request I actually had to use `""` for the `client_secret`.  When I did that it worked.  When I don't do that it doesn't seem to find it in the database.

https://cl.ly/e3a371948744/Screen%20Shot%202019-02-12%20at%2011.26.15%20AM.png

**Comment by danschultzer** [comment]
Is that an empty value or is it actually `""`? It should just be completely empty, and it should work.

**Comment by chasers** [comment]
Yep you're right ... and holy sh*t it worked!

<img width="486" alt="screen shot 2019-02-12 at 12 07 51 pm" src="https://user-images.githubusercontent.com/1019814/52661307-faecd600-2ebe-11e9-9e93-b0a843a8926f.png">
