### ISSUE TITLE
Resource owner was not found with :user assigns

### ISSUE THREAD

**Issue by chasers** [danschultzer/phoenix_oauth2_provider#18]
Almost there!

I'm getting this when I try to oauth in and I'm not logged in.  Everything works logged in.

I'm assuming because I don't have a `:user` in my assigns, like it says, but I'm a bit stuck on how to get one there or how to redirect to a login.  Branch I'm working on is here: https://github.com/Logflare/logflare/tree/oauth2-prov

Thanks again!

**Comment by chasers** [comment]
Okay I kind of have it ... now I need to redirect to a login form and then redirect to the original url.

**Comment by chasers** [comment]
Okay ... put that data in the session which now I can pick out when my user comes back from logging in.

**Comment by danschultzer** [comment]
Great! Yeah, it was because the user hasn't been assigned in the conn.
