### ISSUE TITLE
API only 

### ISSUE THREAD

**Issue by elpic** [danschultzer/phoenix_oauth2_provider#20]
Is there a configuration to use this module as an API only?

For example, if I'm only interested in `grant_type=client_credentials` this option doesn't require a browser interaction, but if I don't add the plug `fetch_session` and `fetch_flash` the call ends up in an error.

**Comment by danschultzer** [comment]
I would recommend just using https://github.com/danschultzer/ex_oauth2_provider and set up your own controllers to manage the flow. For an API with just `client_credentials` you won't need this library.
