### ISSUE TITLE
Authorization code's expire

### ISSUE THREAD

**Issue by guilopes22** [danschultzer/phoenix_oauth2_provider#30]
Hello.

I have a doubt about the authorization code work.

Why it keep expiring? Is there a way to don't need to generate it again and again?

Because sometimes the access token expires and instead just make a request to generate a new access token, I need to generate authorize my application again, get the code and then generate the new access token.

**Comment by danschultzer** [comment]
This is how OAuth 2.0 is required to work. Authorization code [MUST expire](https://tools.ietf.org/html/rfc6749#section-4.1.2).

If the access token is expired you can use a refresh token to generate a new access token. You can [enable refresh token](https://github.com/danschultzer/ex_oauth2_provider/blob/v0.5.5/lib/ex_oauth2_provider.ex#L28-L29) by setting `use_refresh_token: true` in the config. It follows the RFC specs: https://tools.ietf.org/html/rfc6749#section-6

You can also [remove expiration](https://github.com/danschultzer/ex_oauth2_provider/blob/v0.5.5/lib/ex_oauth2_provider.ex#L34-L35) on access tokens by setting `access_token_expires_in: nil` in the config.
