### ISSUE TITLE
Access token's expire

### ISSUE THREAD

**Issue by guilopes22** [danschultzer/phoenix_oauth2_provider#31]
Is there a way to make the access token don't expire?

**Comment by danschultzer** [comment]
Yes, just add `access_token_expires_in: nil` to the config: https://github.com/danschultzer/ex_oauth2_provider/blob/v0.5.5/lib/ex_oauth2_provider.ex#L34-L35

> If access_token_expires_in is set to nil, access tokens will never expire.
