### ISSUE TITLE
Can I disable redirect_uri and authorization token?

### ISSUE THREAD

**Issue by lucasbesen** [danschultzer/phoenix_oauth2_provider#33]
I'm planning to use this lib for server to server authentication, so, I don't need the authorization code and `redirect_uri`.

Is there a way to disable it?

**Comment by danschultzer** [comment]
You can set [the grant flows](https://hexdocs.pm/ex_oauth2_provider/0.5.5/ExOauth2Provider.html) so only `client_credentials` is permitted:

```elixir
grant_flows: ~w(client_credentials)
```
