### ISSUE TITLE
Refresh token isn't generated on client_credentials grant_type

### ISSUE THREAD

**Issue by lucasbesen** [danschultzer/phoenix_oauth2_provider#34]
My configs:
```
grant_flows: ~w(client_credentials),
use_refresh_token: true
```

```
{
    "access_token": "825586b8f3b102090599004cda4d9eeb51433c53b38a124f65e62e7caa9d3424",
    "created_at": "2019-11-12T12:30:49",
    "expires_in": 7200,
    "refresh_token": null,
    "scope": "",
    "token_type": "bearer"
}
```

I'm trying to create a access/refresh token with `client_credentials` grant type but refresh token isn't being generated

**Comment by danschultzer** [comment]
It's not permitted to grant refresh token with `client_credentials` grant type per RFC specs: https://tools.ietf.org/html/rfc6749#section-4.4.3

If you need refresh token you should use the code auth flow.
