### ISSUE TITLE
PhoenixOauth2Provider.ApplicationController.init/1 is undefined

### ISSUE THREAD

**Issue by barberj** [danschultzer/phoenix_oauth2_provider#37]
<img width="1427" alt="Screen Shot 2020-07-17 at 12 52 39 PM" src="https://user-images.githubusercontent.com/503436/87811421-aa547780-c82c-11ea-94d4-48dedc19110e.png">

I ran the generators for both this repo and ex_oauth2_provider. Is the ApplicationController suppose to be manually created and if so do you have directions around its context?

**Comment by danschultzer** [comment]
I think it's because you got it set up as:

```elixir
  scope "/", MaitreDWeb do
    pipe_through :api

    oauth_api_routes()
  end

  scope "/", MaitreDWeb do
    pipe_through [:browser, :protected]

    oauth_routes()
  end
```

You should remove the alias, and just keep it like this:

```elixir
  scope "/" do
    pipe_through :api

    oauth_api_routes()
  end

  scope "/" do
    pipe_through [:browser, :protected]

    oauth_routes()
  end
```

**Comment by barberj** [comment]
Thanks for quick response. That fixed it.
